### ISSUE TITLE
`PostfixConfigGenerator.py` fails on Ubuntu 12.04.5 because of missing `main.cf` file

### ISSUE THREAD

**Issue by azet** [EFForg/starttls-everywhere#25]
The Postfix package in Ubuntu 12.04.5 doesn't seem to contain a `main.cf` file, thus `PostfixConfigGenerator.py` currently fails:

```
(precise)azet@localhost ..tarttls-everywhere/letsencrypt-postfix (git)-[master] % ./PostfixConfigGenerator.py ../examples/starttls-everywhere.json /etc/postfix /etc/letsencrypt/live/example.com
<subprocess.Popen object at 0x1fa5ed0>
Traceback (most recent call last):
  File "./PostfixConfigGenerator.py", line 293, in <module>
    pcgen.deploy_cert("example.com", cert, key, chain, fullchain)
  File "./PostfixConfigGenerator.py", line 188, in deploy_cert
    self.wrangle_existing_config()
  File "./PostfixConfigGenerator.py", line 67, in wrangle_existing_config
    self.raw_cf = open(self.fn).readlines()
IOError: [Errno 2] No such file or directory: '/etc/postfix/main.cf'
1 (precise)azet@localhost ..tarttls-everywhere/letsencrypt-postfix (git)-[master] % lsb_release -a                                                                                          :(No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
(precise)azet@localhost ..tarttls-everywhere/letsencrypt-postfix (git)-[master] % file /etc/postfix/main.cf/etc/postfix/main.cf: ERROR: cannot open `/etc/postfix/main.cf' (No such file or directory)
1 (precise)azet@localhost ..tarttls-everywhere/letsencrypt-postfix (git)-[master] % ls /etc/postfix                                                                                         :(dynamicmaps.cf  master.cf  post-install  postfix-files  postfix-script  sasl
```

@pde mentioned a userbase of about 3%, so we might want to support that version.

This is the package in question: http://packages.ubuntu.com/precise/postfix

**Comment by sydneyli** [comment]
We no longer try to directly wrangle the Postfix config! see repo at [EFForg/starttls-policy-cli](https://github.com/EFForg/starttls-policy-cli)
